/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as environments from "../../../../environments.js";
import * as core from "../../../../core/index.js";
import * as AiInfraApi from "../../../index.js";
import { mergeHeaders, mergeOnlyDefinedHeaders } from "../../../../core/headers.js";
import * as errors from "../../../../errors/index.js";

export declare namespace Sandboxes {
    export interface Options {
        environment?: core.Supplier<environments.AiInfraApiEnvironment | string>;
        /** Specify a custom URL to connect the client to. */
        baseUrl?: core.Supplier<string>;
        token?: core.Supplier<core.BearerToken | undefined>;
        /** Additional headers to include in requests. */
        headers?: Record<string, string | core.Supplier<string | undefined> | undefined>;
    }

    export interface RequestOptions {
        /** The maximum time to wait for a response in seconds. */
        timeoutInSeconds?: number;
        /** The number of times to retry the request. Defaults to 2. */
        maxRetries?: number;
        /** A hook to abort the request. */
        abortSignal?: AbortSignal;
        /** Additional query string parameters to include in the request. */
        queryParams?: Record<string, unknown>;
        /** Additional headers to include in the request. */
        headers?: Record<string, string | core.Supplier<string | undefined> | undefined>;
    }
}

export class Sandboxes {
    protected readonly _options: Sandboxes.Options;

    constructor(_options: Sandboxes.Options = {}) {
        this._options = _options;
    }

    /**
     * List all sandboxes for the authenticated user.
     *
     * @param {Sandboxes.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @example
     *     await client.sandboxes.listSandboxes()
     */
    public listSandboxes(
        requestOptions?: Sandboxes.RequestOptions,
    ): core.HttpResponsePromise<AiInfraApi.SandboxListResponse> {
        return core.HttpResponsePromise.fromPromise(this.__listSandboxes(requestOptions));
    }

    private async __listSandboxes(
        requestOptions?: Sandboxes.RequestOptions,
    ): Promise<core.WithRawResponse<AiInfraApi.SandboxListResponse>> {
        let _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            this._options?.headers,
            mergeOnlyDefinedHeaders({ Authorization: await this._getAuthorizationHeader() }),
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.AiInfraApiEnvironment.Production,
                "sandboxes",
            ),
            method: "GET",
            headers: _headers,
            queryParameters: requestOptions?.queryParams,
            timeoutMs: requestOptions?.timeoutInSeconds != null ? requestOptions.timeoutInSeconds * 1000 : 60000,
            maxRetries: requestOptions?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
        });
        if (_response.ok) {
            return { data: _response.body as AiInfraApi.SandboxListResponse, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            throw new errors.AiInfraApiError({
                statusCode: _response.error.statusCode,
                body: _response.error.body,
                rawResponse: _response.rawResponse,
            });
        }

        switch (_response.error.reason) {
            case "non-json":
                throw new errors.AiInfraApiError({
                    statusCode: _response.error.statusCode,
                    body: _response.error.rawBody,
                    rawResponse: _response.rawResponse,
                });
            case "timeout":
                throw new errors.AiInfraApiTimeoutError("Timeout exceeded when calling GET /sandboxes.");
            case "unknown":
                throw new errors.AiInfraApiError({
                    message: _response.error.errorMessage,
                    rawResponse: _response.rawResponse,
                });
        }
    }

    /**
     * Get a specific sandbox by ID.
     *
     * @param {string} sandboxId
     * @param {Sandboxes.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link AiInfraApi.UnprocessableEntityError}
     *
     * @example
     *     await client.sandboxes.getSandbox("sandbox_id")
     */
    public getSandbox(
        sandboxId: string,
        requestOptions?: Sandboxes.RequestOptions,
    ): core.HttpResponsePromise<AiInfraApi.SandboxResponse> {
        return core.HttpResponsePromise.fromPromise(this.__getSandbox(sandboxId, requestOptions));
    }

    private async __getSandbox(
        sandboxId: string,
        requestOptions?: Sandboxes.RequestOptions,
    ): Promise<core.WithRawResponse<AiInfraApi.SandboxResponse>> {
        let _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            this._options?.headers,
            mergeOnlyDefinedHeaders({ Authorization: await this._getAuthorizationHeader() }),
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.AiInfraApiEnvironment.Production,
                `sandboxes/${encodeURIComponent(sandboxId)}`,
            ),
            method: "GET",
            headers: _headers,
            queryParameters: requestOptions?.queryParams,
            timeoutMs: requestOptions?.timeoutInSeconds != null ? requestOptions.timeoutInSeconds * 1000 : 60000,
            maxRetries: requestOptions?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
        });
        if (_response.ok) {
            return { data: _response.body as AiInfraApi.SandboxResponse, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 422:
                    throw new AiInfraApi.UnprocessableEntityError(
                        _response.error.body as AiInfraApi.HttpValidationError,
                        _response.rawResponse,
                    );
                default:
                    throw new errors.AiInfraApiError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        switch (_response.error.reason) {
            case "non-json":
                throw new errors.AiInfraApiError({
                    statusCode: _response.error.statusCode,
                    body: _response.error.rawBody,
                    rawResponse: _response.rawResponse,
                });
            case "timeout":
                throw new errors.AiInfraApiTimeoutError("Timeout exceeded when calling GET /sandboxes/{sandbox_id}.");
            case "unknown":
                throw new errors.AiInfraApiError({
                    message: _response.error.errorMessage,
                    rawResponse: _response.rawResponse,
                });
        }
    }

    /**
     * Delete a sandbox instance.
     *
     * @param {string} sandboxId
     * @param {Sandboxes.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link AiInfraApi.UnprocessableEntityError}
     *
     * @example
     *     await client.sandboxes.deleteSandbox("sandbox_id")
     */
    public deleteSandbox(
        sandboxId: string,
        requestOptions?: Sandboxes.RequestOptions,
    ): core.HttpResponsePromise<AiInfraApi.DeleteResponse> {
        return core.HttpResponsePromise.fromPromise(this.__deleteSandbox(sandboxId, requestOptions));
    }

    private async __deleteSandbox(
        sandboxId: string,
        requestOptions?: Sandboxes.RequestOptions,
    ): Promise<core.WithRawResponse<AiInfraApi.DeleteResponse>> {
        let _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            this._options?.headers,
            mergeOnlyDefinedHeaders({ Authorization: await this._getAuthorizationHeader() }),
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.AiInfraApiEnvironment.Production,
                `sandboxes/${encodeURIComponent(sandboxId)}`,
            ),
            method: "DELETE",
            headers: _headers,
            queryParameters: requestOptions?.queryParams,
            timeoutMs: requestOptions?.timeoutInSeconds != null ? requestOptions.timeoutInSeconds * 1000 : 60000,
            maxRetries: requestOptions?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
        });
        if (_response.ok) {
            return { data: _response.body as AiInfraApi.DeleteResponse, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 422:
                    throw new AiInfraApi.UnprocessableEntityError(
                        _response.error.body as AiInfraApi.HttpValidationError,
                        _response.rawResponse,
                    );
                default:
                    throw new errors.AiInfraApiError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        switch (_response.error.reason) {
            case "non-json":
                throw new errors.AiInfraApiError({
                    statusCode: _response.error.statusCode,
                    body: _response.error.rawBody,
                    rawResponse: _response.rawResponse,
                });
            case "timeout":
                throw new errors.AiInfraApiTimeoutError(
                    "Timeout exceeded when calling DELETE /sandboxes/{sandbox_id}.",
                );
            case "unknown":
                throw new errors.AiInfraApiError({
                    message: _response.error.errorMessage,
                    rawResponse: _response.rawResponse,
                });
        }
    }

    /**
     * Execute a command in a sandbox.
     *
     * @param {string} sandboxId
     * @param {AiInfraApi.ExecuteRequest} request
     * @param {Sandboxes.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link AiInfraApi.UnprocessableEntityError}
     *
     * @example
     *     await client.sandboxes.execute("sandbox_id", {
     *         command: "command"
     *     })
     */
    public execute(
        sandboxId: string,
        request: AiInfraApi.ExecuteRequest,
        requestOptions?: Sandboxes.RequestOptions,
    ): core.HttpResponsePromise<AiInfraApi.ExecuteResponse> {
        return core.HttpResponsePromise.fromPromise(this.__execute(sandboxId, request, requestOptions));
    }

    private async __execute(
        sandboxId: string,
        request: AiInfraApi.ExecuteRequest,
        requestOptions?: Sandboxes.RequestOptions,
    ): Promise<core.WithRawResponse<AiInfraApi.ExecuteResponse>> {
        let _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            this._options?.headers,
            mergeOnlyDefinedHeaders({ Authorization: await this._getAuthorizationHeader() }),
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.AiInfraApiEnvironment.Production,
                `sandboxes/${encodeURIComponent(sandboxId)}/execute`,
            ),
            method: "POST",
            headers: _headers,
            contentType: "application/json",
            queryParameters: requestOptions?.queryParams,
            requestType: "json",
            body: request,
            timeoutMs: requestOptions?.timeoutInSeconds != null ? requestOptions.timeoutInSeconds * 1000 : 60000,
            maxRetries: requestOptions?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
        });
        if (_response.ok) {
            return { data: _response.body as AiInfraApi.ExecuteResponse, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 422:
                    throw new AiInfraApi.UnprocessableEntityError(
                        _response.error.body as AiInfraApi.HttpValidationError,
                        _response.rawResponse,
                    );
                default:
                    throw new errors.AiInfraApiError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        switch (_response.error.reason) {
            case "non-json":
                throw new errors.AiInfraApiError({
                    statusCode: _response.error.statusCode,
                    body: _response.error.rawBody,
                    rawResponse: _response.rawResponse,
                });
            case "timeout":
                throw new errors.AiInfraApiTimeoutError(
                    "Timeout exceeded when calling POST /sandboxes/{sandbox_id}/execute.",
                );
            case "unknown":
                throw new errors.AiInfraApiError({
                    message: _response.error.errorMessage,
                    rawResponse: _response.rawResponse,
                });
        }
    }

    protected async _getAuthorizationHeader(): Promise<string | undefined> {
        const bearer = await core.Supplier.get(this._options.token);
        if (bearer != null) {
            return `Bearer ${bearer}`;
        }

        return undefined;
    }
}
