/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * @example
 *     {
 *         command: "command"
 *     }
 */
export interface ExecuteRequest {
    /** Command or code to execute */
    command: string;
    /** Execution timeout in seconds */
    timeout?: number;
}
