/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Sandbox from "../index.js";

/**
 * Request to create a new sandbox (type is specified in URL path).
 */
export interface CreateSandboxRequest {
    /** Provider to use (auto-detected if not specified) */
    provider?: Sandbox.SandboxProvider;
    /** Preferred region for the sandbox */
    region?: string;
    /** Timeout in minutes */
    timeout?: number;
    /** Additional metadata */
    metadata?: Record<string, any>;
}
