/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * Response for delete operations.
 */
export interface DeleteResponse {
    success: boolean;
    message: string;
    sandbox_id: string;
}
