/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * Response from command execution.
 */
export interface ExecuteResponse {
    stdout?: string;
    stderr?: string;
    exit_code?: number;
    error?: string;
}
