/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * Health status information.
 */
export interface HealthStatus {
    /** Whether the service is healthy */
    is_healthy: boolean;
    /** Health status description */
    status: string;
    details?: Record<string, any>;
    checked_at?: string;
}
