/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * Resource limits response.
 */
export interface LimitsResponse {
    limits: Record<string, number>;
    current_usage: Record<string, number>;
    timestamp: string;
}
