/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * Available regions response.
 */
export interface RegionsResponse {
    regions: Record<string, Record<string, any>>;
}
