/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * Sandbox provider.
 */
export type SandboxProvider = "e2b" | "volcengine" | "aws" | "alibaba";
export const SandboxProvider = {
    E2B: "e2b",
    Volcengine: "volcengine",
    Aws: "aws",
    Alibaba: "alibaba",
} as const;
