/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as AiInfraApi from "../index.js";

/**
 * Response containing sandbox details.
 */
export interface SandboxResponse {
    id: string;
    type: string;
    provider: string;
    region?: string;
    status: string;
    created_at: string;
    expires_at?: string;
    urls?: AiInfraApi.SandboxUrls;
    timeout?: number;
}
