/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as AiInfraApi from "../index.js";

/**
 * Response for listing sandboxes.
 */
export interface SandboxListResponse {
    sandboxes: AiInfraApi.SandboxResponse[];
    total: number;
}
