/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * Request to execute a command in a sandbox.
 */
export interface ExecuteRequest {
    /** Command or code to execute */
    command: string;
    /** Execution timeout in seconds */
    timeout?: number;
}
