/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * URLs associated with a sandbox.
 */
export interface SandboxUrls {
    wss_url?: string;
    vnc_url?: string;
    mcp_url?: string;
    api_url?: string;
}
