/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * Response containing token details.
 */
export interface TokenResponse {
    id: string;
    user_id: string;
    name: string;
    token_prefix: string;
    scopes: string[];
    created_at: string;
    expires_at?: string;
    revoked_at?: string;
    last_used_at?: string;
    display_token?: string;
    raw_token?: string;
}
