/**
 * This file was auto-generated by Fern from our API Definition.
 */

export const AiInfraApiEnvironment = {
    Production: "https://api.sandbox.ai-infra.org",
} as const;

export type AiInfraApiEnvironment = typeof AiInfraApiEnvironment.Production;
