/**
 * This file was auto-generated by Fern from our API Definition.
 */

export class AiInfraApiTimeoutError extends Error {
    constructor(message: string) {
        super(message);
        Object.setPrototypeOf(this, AiInfraApiTimeoutError.prototype);
    }
}
