/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as environments from "./environments.js";
import * as core from "./core/index.js";
import { mergeHeaders, mergeOnlyDefinedHeaders } from "./core/headers.js";
import * as Sandbox from "./api/index.js";
import * as errors from "./errors/index.js";
import { CodeInterpreter } from "./api/resources/codeInterpreter/client/Client.js";
import { Browser } from "./api/resources/browser/client/Client.js";
import { Aio } from "./api/resources/aio/client/Client.js";
import { Sandboxes } from "./api/resources/sandboxes/client/Client.js";
import { Tokens } from "./api/resources/tokens/client/Client.js";

export declare namespace SandboxClient {
    export interface Options {
        environment?: core.Supplier<environments.SandboxEnvironment | string>;
        /** Specify a custom URL to connect the client to. */
        baseUrl?: core.Supplier<string>;
        token?: core.Supplier<core.BearerToken | undefined>;
        /** Additional headers to include in requests. */
        headers?: Record<string, string | core.Supplier<string | undefined> | undefined>;
    }

    export interface RequestOptions {
        /** The maximum time to wait for a response in seconds. */
        timeoutInSeconds?: number;
        /** The number of times to retry the request. Defaults to 2. */
        maxRetries?: number;
        /** A hook to abort the request. */
        abortSignal?: AbortSignal;
        /** Additional query string parameters to include in the request. */
        queryParams?: Record<string, unknown>;
        /** Additional headers to include in the request. */
        headers?: Record<string, string | core.Supplier<string | undefined> | undefined>;
    }
}

export class SandboxClient {
    protected readonly _options: SandboxClient.Options;
    protected _codeInterpreter: CodeInterpreter | undefined;
    protected _browser: Browser | undefined;
    protected _aio: Aio | undefined;
    protected _sandboxes: Sandboxes | undefined;
    protected _tokens: Tokens | undefined;

    constructor(_options: SandboxClient.Options = {}) {
        this._options = {
            ..._options,
            headers: mergeHeaders(
                {
                    "X-Fern-Language": "JavaScript",
                    "X-Fern-Runtime": core.RUNTIME.type,
                    "X-Fern-Runtime-Version": core.RUNTIME.version,
                },
                _options?.headers,
            ),
        };
    }

    public get codeInterpreter(): CodeInterpreter {
        return (this._codeInterpreter ??= new CodeInterpreter(this._options));
    }

    public get browser(): Browser {
        return (this._browser ??= new Browser(this._options));
    }

    public get aio(): Aio {
        return (this._aio ??= new Aio(this._options));
    }

    public get sandboxes(): Sandboxes {
        return (this._sandboxes ??= new Sandboxes(this._options));
    }

    public get tokens(): Tokens {
        return (this._tokens ??= new Tokens(this._options));
    }

    /**
     * Check service health status.
     *
     * @param {SandboxClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @example
     *     await client.checkHealth()
     */
    public checkHealth(requestOptions?: SandboxClient.RequestOptions): core.HttpResponsePromise<Sandbox.HealthStatus> {
        return core.HttpResponsePromise.fromPromise(this.__checkHealth(requestOptions));
    }

    private async __checkHealth(
        requestOptions?: SandboxClient.RequestOptions,
    ): Promise<core.WithRawResponse<Sandbox.HealthStatus>> {
        let _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            this._options?.headers,
            mergeOnlyDefinedHeaders({ Authorization: await this._getAuthorizationHeader() }),
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.SandboxEnvironment.Production,
                "health",
            ),
            method: "GET",
            headers: _headers,
            queryParameters: requestOptions?.queryParams,
            timeoutMs: requestOptions?.timeoutInSeconds != null ? requestOptions.timeoutInSeconds * 1000 : 60000,
            maxRetries: requestOptions?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
        });
        if (_response.ok) {
            return { data: _response.body as Sandbox.HealthStatus, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            throw new errors.SandboxError({
                statusCode: _response.error.statusCode,
                body: _response.error.body,
                rawResponse: _response.rawResponse,
            });
        }

        switch (_response.error.reason) {
            case "non-json":
                throw new errors.SandboxError({
                    statusCode: _response.error.statusCode,
                    body: _response.error.rawBody,
                    rawResponse: _response.rawResponse,
                });
            case "timeout":
                throw new errors.SandboxTimeoutError("Timeout exceeded when calling GET /health.");
            case "unknown":
                throw new errors.SandboxError({
                    message: _response.error.errorMessage,
                    rawResponse: _response.rawResponse,
                });
        }
    }

    /**
     * List available regions for all providers.
     *
     * @param {SandboxClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @example
     *     await client.listRegions()
     */
    public listRegions(requestOptions?: SandboxClient.RequestOptions): core.HttpResponsePromise<any> {
        return core.HttpResponsePromise.fromPromise(this.__listRegions(requestOptions));
    }

    private async __listRegions(requestOptions?: SandboxClient.RequestOptions): Promise<core.WithRawResponse<any>> {
        let _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            this._options?.headers,
            mergeOnlyDefinedHeaders({ Authorization: await this._getAuthorizationHeader() }),
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.SandboxEnvironment.Production,
                "regions",
            ),
            method: "GET",
            headers: _headers,
            queryParameters: requestOptions?.queryParams,
            timeoutMs: requestOptions?.timeoutInSeconds != null ? requestOptions.timeoutInSeconds * 1000 : 60000,
            maxRetries: requestOptions?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
        });
        if (_response.ok) {
            return { data: _response.body, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            throw new errors.SandboxError({
                statusCode: _response.error.statusCode,
                body: _response.error.body,
                rawResponse: _response.rawResponse,
            });
        }

        switch (_response.error.reason) {
            case "non-json":
                throw new errors.SandboxError({
                    statusCode: _response.error.statusCode,
                    body: _response.error.rawBody,
                    rawResponse: _response.rawResponse,
                });
            case "timeout":
                throw new errors.SandboxTimeoutError("Timeout exceeded when calling GET /regions.");
            case "unknown":
                throw new errors.SandboxError({
                    message: _response.error.errorMessage,
                    rawResponse: _response.rawResponse,
                });
        }
    }

    /**
     * Get resource limits and current usage.
     *
     * @param {SandboxClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @example
     *     await client.getLimits()
     */
    public getLimits(requestOptions?: SandboxClient.RequestOptions): core.HttpResponsePromise<Sandbox.LimitsResponse> {
        return core.HttpResponsePromise.fromPromise(this.__getLimits(requestOptions));
    }

    private async __getLimits(
        requestOptions?: SandboxClient.RequestOptions,
    ): Promise<core.WithRawResponse<Sandbox.LimitsResponse>> {
        let _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            this._options?.headers,
            mergeOnlyDefinedHeaders({ Authorization: await this._getAuthorizationHeader() }),
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.SandboxEnvironment.Production,
                "limits",
            ),
            method: "GET",
            headers: _headers,
            queryParameters: requestOptions?.queryParams,
            timeoutMs: requestOptions?.timeoutInSeconds != null ? requestOptions.timeoutInSeconds * 1000 : 60000,
            maxRetries: requestOptions?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
        });
        if (_response.ok) {
            return { data: _response.body as Sandbox.LimitsResponse, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            throw new errors.SandboxError({
                statusCode: _response.error.statusCode,
                body: _response.error.body,
                rawResponse: _response.rawResponse,
            });
        }

        switch (_response.error.reason) {
            case "non-json":
                throw new errors.SandboxError({
                    statusCode: _response.error.statusCode,
                    body: _response.error.rawBody,
                    rawResponse: _response.rawResponse,
                });
            case "timeout":
                throw new errors.SandboxTimeoutError("Timeout exceeded when calling GET /limits.");
            case "unknown":
                throw new errors.SandboxError({
                    message: _response.error.errorMessage,
                    rawResponse: _response.rawResponse,
                });
        }
    }

    protected async _getAuthorizationHeader(): Promise<string | undefined> {
        const bearer = await core.Supplier.get(this._options.token);
        if (bearer != null) {
            return `Bearer ${bearer}`;
        }

        return undefined;
    }
}
