/**
 * This file was auto-generated by Fern from our API Definition.
 */

export const SandboxEnvironment = {
    Production: "https://api.sandbox.ai-infra.org",
} as const;

export type SandboxEnvironment = typeof SandboxEnvironment.Production;
