/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * @example
 *     {
 *         name: "name",
 *         user_id: "user_id"
 *     }
 */
export interface CreateTokenRequest {
    "X-Admin-Key"?: string;
    /** Token name */
    name: string;
    /** User ID */
    user_id: string;
    /** Token scopes */
    scopes?: string[];
    /** Token expiration in days */
    expires_in_days?: number;
    /** Revoke existing tokens for user */
    revoke_existing?: boolean;
}
